// Customizer const
export const TOGGLE_COLLAPSED_NAV = 'TOGGLE_COLLAPSE_MENU';
export const WINDOW_WIDTH = 'WINDOW-WIDTH';
export const SWITCH_LANGUAGE = 'SWITCH-LANGUAGE';

//Contact Module const
export const ADMIT_LIST = 'ADMIT_LIST';
export const FETCH_START = 'fetch_start';
export const FETCH_SUCCESS = 'fetch_success';
export const FETCH_ERROR = 'fetch_error';
export const SHOW_MESSAGE = 'SHOW_MESSAGE';
export const CLEAR_SHOW_MESSAGE = 'CLEAR_SHOW_MESSAGE';
export const PATIENT_TYPE = 'PATIENT_TYPE';
export const TypeAndPatient = 'TypeAndPatient';
export const SELECT_PATIENT = 'SELECT_PATIENT';
export const CLEAR_SELECT_PATIENT = 'CLEAR_SELECT_PATIENT';
export const CLEAR_SELECT_OPD_PATIENT = 'CLEAR_SELECT_OPD_PATIENT';
export const SELECT_OPD_PATIENT = 'SELECT_OPD_PATIENT';
export const SELECT_WORK_ROOM = 'SELECT_WORK_ROOM';
export const SELECT_LAB_PATIENT_ID = 'SELECT_LAB_PATIENT_ID';
export const SELECT_X_RAY_PATIENT_ID = 'SELECT_X_RAY_PATIENT_ID';
export const SELECT_SCREENING_PATIENT = 'SELECT_SCREENING_PATIENT';
export const SERVICE_LIST = 'SERVICE_LIST';
export const HIDE_MESSAGE = 'HIDE_MESSAGE';
export const ON_SHOW_LOADER = 'ON_SHOW_LOADER';
export const ON_HIDE_LOADER = 'ON_HIDE_LOADER';

//Auth const
export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNIN_GOOGLE_USER = 'SIGNIN_GOOGLE_USER';
export const SIGNIN_GOOGLE_USER_SUCCESS = 'SIGNIN_GOOGLE_USER_SUCCESS';
export const SIGNIN_FACEBOOK_USER = 'SIGNIN_FACEBOOK_USER';
export const SIGNIN_FACEBOOK_USER_SUCCESS = 'SIGNIN_FACEBOOK_USER_SUCCESS';
export const SIGNIN_TWITTER_USER = 'SIGNIN_TWITTER_USER';
export const SIGNIN_TWITTER_USER_SUCCESS = 'SIGNIN_TWITTER_USER_SUCCESS';
export const SIGNIN_GITHUB_USER = 'SIGNIN_GITHUB_USER';
export const SIGNIN_GITHUB_USER_SUCCESS = 'signin_github_user_success';
export const SIGNIN_USER = 'SIGNIN_USER';
export const SIGNIN_USER_SUCCESS = 'SIGNIN_USER_SUCCESS';
export const SIGNOUT_USER = 'SIGNOUT_USER';
export const SIGNOUT_USER_SUCCESS = 'SIGNOUT_USER_SUCCESS';
export const INIT_URL = 'INIT_URL';
export const USER_DATA = 'user_data';
export const USER_TOKEN_SET = 'user_token_set';
export const UPDATE_LOAD_USER = 'UPDATE_LOAD_USER';

//WorkRoom
export const OPDCLINIC_ROOM = 'OPDCLINIC_ROOM';
export const DENTAL_ROOM = 'DENTAL_ROOM';
export const DOCTORCLINIC_ROOM = 'DOCTORCLINIC_ROOM';
export const WARD_ROOM = 'WARD_ROOM';
export const LABORATORY_ROOM = 'LABORATORY_ROOM';
export const OPDPRESCRIPTION_ROOM = 'OPDPRESCRIPTION_ROOM';
export const IPDPRESCRIPTION_ROOM = 'IPDPRESCRIPTION_ROOM';
export const Operation_ROOM = 'Operation_ROOM';
export const INVENTORY_ROOM = 'INVENTORY_ROOM';
export const QUEUE_ROOM = 'QUEUE_ROOM';
export const PSYCHIATRIC_ROOM = 'PSYCHIATRIC_ROOM';

//GenFrom
export const GETGENFROMDATATABEL = 'GETGENFROMDATATABEL';
export const CLEARGENFROMDATATABEL = 'CLEARGENFROMDATATABEL';

//Menu 11
export const WARD_MENU = 'WARD_MENU';

//DRUG INFO 16.1
export const DRUG_INFO_BY_ID = 'DRUG_INFO_BY_ID'

//Menu 18
export const SELECT_OPERATION_SET = 'SELECT_OPERATION_SET';
export const RESET_DRUG_INFO = 'RESET_DRUG_INFO'
export const EDIT_DRUG_INFO = 'EDIT_DRUG_INFO'

// Smart Card
export const SMART_CARD = 'SMART_CARD';
export const SMART_CARD_CLEAR = 'SMART_CARD_CLEAR';

export const MODULE_ID = 'MODULE_ID';

// Notification
export const FETCH_NOTI = 'FETCH_NOTI'

//Scanner
export const PATIENT_SCANNER = 'PATIENT_SCANNER';

//  MENU 13
export const X_RAY_WORK_ID = 'X_RAY_WORK_ID';

//20.1
export const OPD_FINANCE_PLACE = 'OPD_FINANCE_PLACE';
//21.1
export const IPD_FINANCE_PLACE = 'IPD_FINANCE_PLACE';

//34.7
export const GET_ASSESSMENT_CODE = 'GET_ASSESSMENT_CODE';

//57.1
export const GET_WARD_AND_BEDTYPE = 'GET_WARD_AND_BEDTYPE';

// All Saerch
export const SELECT_ALL_SEARCH = 'SELECT_ALL_SEARCH';

export const HOSPITAL_PARAM_SET = 'HOSPITAL_PARAM_SET';

//35
export const RISK_MANAGEMENT = 'RISK_MANAGEMENT';

// Master 
export const GET_ICDS = 'GET_ICDS';
export const GET_ICD10_IT = 'GET_ICD10_IT';
export const GET_ICD9_CM = 'GET_ICD9_CM';
export const GET_USER_ALL = 'GET_USER_ALL';
export const GET_HOSP_CODE = 'GET_HOSP_CODE';
export const GET_EXPENSE = 'GET_EXPENSE';
export const GET_ICD10_PURE = 'GET_ICD10_PURE';
export const GET_ICD9_PURE = 'GET_ICD9_PURE';
export const SET_DRUG_USING_LIST = 'SET_DRUG_USING_LIST';
export const SET_UNIT_LIST = 'SET_UNIT_LIST';
export const SET_DRUG_TIMING_LIST = 'SET_DRUG_TIMING_LIST';
export const SET_DOSING_TIME = 'SET_DOSING_TIME';
export const SET_DOSING_INTERVAL = 'SET_DOSING_INTERVAL';
export const SET_DRUG_PROPERTY = 'SET_DRUG_PROPERTY';
export const SET_DRUG_WARNING = 'SET_DRUG_WARNING';
export const SET_DRUG_ADMIN = 'SET_DRUG_ADMIN';
export const SET_ISED_REASON = 'SET_ISED_REASON';
export const SET_DRUG_TYPE_LIST = 'SET_DRUG_TYPE_LIST';
export const SET_DRUG_LIST = 'SET_DRUG_LIST';
export const SET_FINANCE_TYPES = 'SET_FINANCE_TYPES';
export const SET_EXPENSE_LIST_WITH_TYPES = 'SET_EXPENSE_LIST_WITH_TYPES';
export const SET_EXPENSE_ORDERS = 'SET_EXPENSE_ORDERS';
export const SET_EXPENSE_LABS = 'SET_EXPENSE_LABS';
export const SET_EXPENSE_XRAYS = 'SET_EXPENSE_XRAYS';


//Sound
export const ADD_SOUND = 'ADD_SOUND'

//35
export const TEMP_INC_ID = 'TEMP_INC_ID'