export * from './Setting';
export * from './Common';
export * from './AdmitDischarge';
export * from './Autocomplete';
export * from './Patient';
export * from './Ward';
export * from './Drug'
export * from './Notification'
export * from './PatientScanner'
export * from './XRayWorkId'
export * from './OpdFinancePlace'
export * from './IpdFinancePlace'
export * from './WorkRoom'
export * from './Search'
export * from './GenFromDataTable'
export * from './DropdownMaster'
export * from './HealthCheckup'
export * from './Sound'
export * from './BedManagement'
export * from './RiskManagement'
export * from './TempData'
export * from './Dropdowns'